### ISSUE TITLE
Make octoffers a Directly Executable CLI

### ISSUE THREAD

**Issue by webgtx** [init64/octoffers#14]
**Description:**

Currently, users need to run `octoffers` with `python` (e.g., `python octoffers help`). We need to configure the project so users can run it directly (e.g., `octoffers help`).

**Expected Behavior:**
Users should be able to run `octoffers` without `python` in command line.

Like this: 
```bash
octoffers help # not $ python octoffers help
```

**Steps to Reproduce:**
1. Install `octoffers`.
2. Try running `octoffers help`.
3. It won't work.

**Example**:
You can use my Python project named todomanager as an example. It is well-configured according to the latest PEP standards. 
<div align=center>

[webgtx/todomanager](https://github.com/webgtx/todomanager)

<div>

**Comment by swarupn17** [comment]
Hey @webgtx I can do this task please can you assign it to me !
Thanks.

**Comment by webgtx** [comment]
Hi @swarupn17. Currently, @oebelus is working on this issue, but he has encountered an issue with imports, see #18 . **So, if you can get your PR merged before him, you can claim this issue.** 

### Goodluck :shipit:

**Comment by webgtx** [comment]
#18
