### ISSUE TITLE
Create code_of_conduct.md 

### ISSUE THREAD

**Issue by KirtiPratihar** [init64/octoffers#19]
Hi ! I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext, hacktoberfest-accepted Labels.

Thanks

**Comment by webgtx** [comment]
Hi @KirtiPratihar, first of all thank you for reaching out.

Now, while I'm open to suggestions, feature requests, and PRs, I can't guarantee that I will merge the **code of conduct** right away. It might take some time for me to consider it and possibly make some changes on my side.

**Comment by webgtx** [comment]
Hey @KirtiPratihar, any updates? :shipit:
